Feature/header
Ray-Janson/AirRecipes2.0 pull request #2
Opened 2022-10-02 06:28 UTC by Ray-Janson

- Implemented Header and FilterForm layouts
- Implemented Header scroll behavior
- Implemented global state and requests for getting filters data required for FilterForm

2022-10-04 05:34 UTC, alinadk12 requested changes

2022-10-04 05:34 UTC, alinadk12 commented on src/components/default-components/round-button/RoundButtonController.jsx
> +import React from 'react';
Извини, если не очень понятно написала в первый раз - названия директорий пишутся с маленькой буквы, но в lowerCamelCase

2022-10-04 05:34 UTC, alinadk12 commented on src/components/default-components/round-button/styles/RoundButton.module.scss
> +  background-color: #fff;
вынеси все цвета в константы, а то смотрится не очень, когда часть цветов вынесено, а другая часть пишется как есть

2022-10-04 05:34 UTC, alinadk12 commented on src/components/filter-form/FilterFormController.jsx
> +    changedCuisineFilter.status = !changedCuisineFilter.status;
нужна проверка на случай, если `changedCuisineFilter` не будет найден

2022-10-04 05:34 UTC, alinadk12 commented on src/components/header/HeaderController.jsx
> +    if (rectImage.bottom > rectInput.top + rectInput.height / 2 + 10) {
`rectInput.top + rectInput.height / 2 + 10` вынеси в отдельную переменную, чтоб было легче читать, и чтоб было понятно что это

2022-10-04 05:34 UTC, alinadk12 commented on src/components/header/header-scroll-behavior/HeaderScrollBehavior.js
> +import styles from '../styles/Header.module.scss';
этот файл похож на хелпер, будет понятней, если он будет лежать в папке `helpers` или т.п. 
Также с большой буквы называются файлы с реакт компонентами, в данном случае файл должен называться `headerScrollBehavior`

2022-10-04 05:34 UTC, alinadk12 commented on src/components/header/styles/Header.module.scss
> +  background-color: #fff;
вынеси везде этот цвет в константу

2022-10-04 05:34 UTC, alinadk12 commented on src/index.jsx
> +import './assets/fonts/Gilroy/stylesheet.scss';
в импортах мы обычно тоже стараемся соблюдать порядок - первым должен быть импорт из реакта (если он нужен), потом импорты из подключенных библиотек. Импорты из `material-ui` тоже выносим отдельно, после подключенных библиотек. Относительные импорты идут последними и через отступ от остальных импортов. На правильность кода это никак не влияет, но это влияет на порядок в коде и на читабельность. Т.е. в данном файле импорты должны выглядеть так:

```
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Provider } from 'react-redux';
import { BrowserRouter } from 'react-router-dom';

import { ThemeProvider } from '@mui/material';

import store from './models/store/index';
import App from './App';
import reportWebVitals from './reportWebVitals';
import theme from './theme/theme';
import './assets/fonts/Gilroy/stylesheet.scss';
import './index.scss';
```

2022-10-04 05:34 UTC, alinadk12 commented on src/models/store/slices/recipeSlice.js
> +      return `${hours} hours`;
разделяй код отступами, так сложно читается

```
if (seconds < 60) return `${seconds} sec`;

const minutes = seconds / 60;
if (minutes < 60) return `${minutes} min`;

const hours = minutes / 60;
return `${hours} hours`;
```

2022-10-04 06:53 UTC, Ray-Janson commented on src/components/filter-form/FilterFormController.jsx
> +    changedCuisineFilter.status = !changedCuisineFilter.status;
Вообще таких случаев быть не должно, но на всякий случай выкину ошибку.

2022-10-05 04:01 UTC, alinadk12 commented on src/components/filter-form/FilterFormController.jsx
> +    changedCuisineFilter.status = !changedCuisineFilter.status;
Очень часто бывает, что код пишется с мыслью "таких случаев быть не должно", но очень часто эти случаи потом появляются и это перетекает в баги

2022-10-05 04:05 UTC, alinadk12 approved these changes

2022-10-05 05:29 UTC, merged