Port project to mobx and implement clean architecture
Ray-Janson/AirRecipes2.0 pull request #6
Opened 2022-10-26 20:14 UTC by Ray-Janson

2022-10-27 10:38 UTC, alinadk12 requested changes

2022-10-27 10:38 UTC, alinadk12 commented on .eslintrc.json
> +                        "pattern": "@react-pdf/**",
Тебе это точно в настройках надо ? Удали пути, которые ты не используешь

2022-10-27 10:38 UTC, alinadk12 commented on src/components/defaultComponents/modal/ModalController.tsx
> +      sleep(200).then(() => {
не забывай разделять код логическими отступами

2022-10-27 10:38 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +import { observer } from 'mobx-react';
mobx-react-lite для текущих нужд тоже подойдет, но весит он при этом меньше, так что лучше его использовать
`import { observer } from 'mobx-react-lite'`

2022-10-27 10:38 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    setState((prevState) => ({ ...prevState, cuisinesFilter: newCuisinesFilter }));
а не проще использовать 2 разных стейта для `sliderValue` и `cuisinesFilter` ? Тогда не придется писать такие избыточные конструкции для обновления стейта и данные не будут храниться в одной куче, а будут логически разделены. Ты можешь в одном компоненте использовать несколько хуков useState, они не будут мешать друг другу

2022-10-27 10:38 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
>      setIsModalOpened(false);
отступ

2022-10-27 10:38 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    setIsModalOpened(false);
отступ

2022-10-27 10:38 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +  const getIsFilterChanged = () => !!(state.cuisinesFilter.find((x) => !x.status)
ты можешь сразу обернуть это в useMemo, не вынося в лишнюю функцию
```
const isFilterChanged = useMemo(
    () => !!(state.cuisinesFilter.find((x) => !x.status) 
      || state.sliderValue[0] !== CAL_SLIDER_MIN_VALUE
      || state.sliderValue[1] !== CAL_SLIDER_MAX_VALUE),
    [state.cuisinesFilter, state.sliderValue],
  );
```

2022-10-27 10:38 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +const getDefaultCuisinesFilter = (cuisines: ICuisine[] | null) => (
вынеси лучше в отдельной хэлпер, можешь в этой же папке создать папку helpers, и там создать файл и вынести туда эту функцию

2022-10-27 10:38 UTC, alinadk12 commented on src/components/header/HeaderController.tsx
> +import { observer } from 'mobx-react';
`mobx-react-lite`

2022-10-27 10:38 UTC, alinadk12 commented on src/components/recipe/RecipeController.tsx
> +  return (
отступы

2022-10-27 10:38 UTC, alinadk12 commented on src/components/recipesList/RecipesListController.tsx
> +import { observer } from 'mobx-react';
`mobx-react-lite`

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/entity/recipe/Difficulty.ts
> +export type Difficulty = 'easy' | 'medium' | 'hard';
лучше в набор enum переделать, чтоб потом в коде не голый текст мелькал, так читаться лучше потом будет

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +    return this.cuisines;
ты можешь переименовать поле cuisines в _cuisines, а метод получения значения сделать полноценным геттером

```
@observable private _cuisines: ICuisine[] | null = null;

public get cuisines(): ICuisine[] | null {
    return this._cuisines;
}
```
Это чисто вкусовщина и твой вариант тоже правильный. По мне - так смотрится лучше. Править или нет - решай сам)

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +    return this.cuisines;
и проверь консоль на варнинги, скорей всего там куча варнингов, что читаешь данные вне контекста. Если так, то используй метод toJS от mobx, чтобы переделать массив в читабельный формат для js. В таком случае метод будет выглядеть так
```
public get cuisines(): ICuisine[] | null {
    return toJS(this._cuisines);
}
```

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +        recipes = recipes.filter((x) => cuisinesIds.includes(x.cuisine.id));
отступ

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +      if (filters.cuisinesFilter) {
отступ

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +      if (filters.calFilter) {
отступ

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/interactors/filters/ApplyFiltersUseCase.ts
> +    await this.getRecipesUseCase.fetchFilteredRecipes(filters);
отступ

2022-10-27 10:38 UTC, alinadk12 commented on src/domain/interactors/recipes/GetRecipesUseCase.ts
> +    this.recipesStore.onFetchRecipes(response, filters);
отступ

2022-10-28 07:48 UTC, Ray-Janson commented on src/components/filterForm/FilterFormController.tsx
> +    setState((prevState) => ({ ...prevState, cuisinesFilter: newCuisinesFilter }));
Изначально у меня они были разделены. Но затем в коде появились места, где нужно одновременно поменять сразу два этих стейта. Вроде бы в 17-18 версиях реакта завезли batching (когда несколько setState'ов объединяются в один), но у меня это как-то непредсказуемо работало. Второе изменение то применялось, то нет. Поэтому для надежности я просто решил все в один стейт объединить.

2022-10-28 08:15 UTC, Ray-Janson commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +    return this.cuisines;
Вообще варнингов не было, но исходя из документации observable объекты лучше оборачивать в эту функцию, поэтому все равно добавил

2022-11-02 03:04 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    setState((prevState) => ({ ...prevState, cuisinesFilter: newCuisinesFilter }));
в таком случае почитай про хук `useReducer`, возможно он тебе больше подойдет

2022-11-02 04:17 UTC, alinadk12 requested changes

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +  const [state, setState] = React.useState<FilterFormControllerState>({
импортни useState отдельно

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +  React.useEffect(() => {
импортни useEffect отдельно

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +  }, [cuisines]);
а почему у тебя в зависимостях `cuisines`, но при это для обновления стейта больше используются значения `filters` ?

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +  const cuisines = viewModel.getCuisines();
ты можешь во `viewModel` использовать полноценные геттеры, например, вместо `getCuisines`  геттер будет выглядеть так: 
```
public get cuisines(): ICuisine[] | null {
    return this.store.cuisines;
  }
```

в таком случае для получения значения `cuisines` нужна будет такая запись
`const { cuisines } = viewModel;`
Это удобно, если тебе, например, понадобиться сразу вытащить несколько значений, например,
`const { cuisines, filters } = viewModel;`

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    actualizeLocalState();
Почитай, почему так делать не стоит https://ru.reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies 
Может у тебя получится более понятно код организовать

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/components/cuisinesFilterList/CuisinesFilterListController.tsx
>    const curCuisinesFiltersStatus: CuisineFilterStatus | undefined = useMemo(
```
const curCuisinesFiltersStatus: CuisineFilterStatus | undefined = useMemo(
    () => cuisinesFilter?.reduce((acc, item) => ({ ...acc, [item.id]: item.status }), {}),
    [cuisinesFilter],
  );
```

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/helpers/getDefaultCuisinesFilter.ts
> +export const getDefaultCuisinesFilter = (cuisines: ICuisine[] | null) => (
export const getDefaultCuisinesFilter = (cuisines: ICuisine[] | null): **ICuisineFilter[]** => (

2022-11-02 04:17 UTC, alinadk12 commented on src/components/filterForm/helpers/getDefaultCuisinesFilter.ts
> +      { id: item.id, status: true } as ICuisineFilter))
`as ICuisineFilter` тут не нужен

2022-11-02 04:17 UTC, alinadk12 commented on src/components/recipe/RecipeViewModel.ts
> +  public getRecipeDetails() {
```
public get recipeDetails() {
    return this.store.recipeDetails;
  }
```

2022-11-02 04:17 UTC, alinadk12 commented on src/components/recipe/RecipeController.tsx
> +  const recipeDetails = viewModel.getRecipeDetails();
`const { recipeDetails, fetchRecipeDetails } = viewModel;`

2022-11-02 04:17 UTC, alinadk12 commented on src/components/recipe/RecipeController.tsx
> +      viewModel.fetchRecipeDetails(+params.recipeId);
функция `fetchRecipeDetails` асинхронная, соответственное вызывать ее стоит вместе с `await`

```
useEffect(() => {
    (async () => {
      if (params.recipeId) {
        await fetchRecipeDetails(+params.recipeId);
      }
    })();
  }, [params.recipeId]);
```

2022-11-02 04:17 UTC, alinadk12 commented on src/components/recipesList/RecipesListController.tsx
> +  const recipes = viewModel.getRecipes();
`const { recipes, fetchRecipes } = viewModel;`

2022-11-02 04:17 UTC, alinadk12 commented on src/components/recipesList/RecipesListController.tsx
> +      viewModel.fetchRecipes();
```
useEffect(() => {
    (async () => {
      if (!recipes) {
        await fetchRecipes();
      }
    })();
  }, []);
```

2022-11-02 04:17 UTC, alinadk12 commented on src/components/recipesList/RecipesListViewModel.ts
> +  public getRecipes(): IRecipe[] | null {
```
public get recipes(): IRecipe[] | null {
    return this.store.filteredRecipes;
  }
```

2022-11-02 04:17 UTC, alinadk12 commented on src/domain/entity/recipe/Difficulty.ts
> +  Easy = 'easy',
у енумов ключи всегда в капсе
```
export enum Difficulty {
  EASY = 'easy',
  MEDIUM = 'medium',
  HARD = 'hard',
}
```

2022-11-02 06:14 UTC, Ray-Janson commented on src/components/filterForm/FilterFormController.tsx
> +  }, [cuisines]);
В стейте с фильтрами содержится фильтр по кухне (китайская, индийская ...), поэтому стейт фильтров зависит от списка возможных кухонь. Если список кухонь меняется (к примеру, наконец-то они прилетают с сервера), то нужно обновить фильтры.

2022-11-02 07:59 UTC, Ray-Janson commented on src/components/recipe/RecipeController.tsx
> +  const recipeDetails = viewModel.getRecipeDetails();
функции лучше через деструктуризацию не получать, потому что тогда у них теряется `this`.

2022-11-07 10:57 UTC, alinadk12 requested changes

2022-11-07 10:57 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    case ActionType.UPDATE_FILTERS:
У тебя 3 разных варианта обновления стейта - обновить только sliderValue, или только cuisinesFilter, или сразу оба, а ты все запихал в один кейс. Можно же разложить на три разных кейса и в payload передавать только newValue. А в текущем варианте у тебя от useState не сильно отличается

2022-11-07 10:57 UTC, alinadk12 commented on src/components/filterForm/types.ts
> +  payload?: any,
`any` надо стараться не использовать

2022-11-07 10:57 UTC, alinadk12 commented on src/components/filterForm/types.ts
> +  type: string,
`type` должен быть набором енумов

2022-11-07 10:57 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    dispatch(getUpdateFilterAction({
код слипся, отступ

2022-11-07 10:57 UTC, alinadk12 commented on src/data/RecipeDetailsApi.ts
> +      .then((response) => response.data.recipe as IRecipeDetails)
`interface RecipeDetailsResponse { recipe: IRecipeDetails }`

...

`.then((response: AxiosResponse<RecipeDetailsResponse>) => response.data.recipe)`

2022-11-07 10:57 UTC, alinadk12 commented on src/data/RecipesListApi.ts
> +      .then((response) => response.data.recipes as IRecipe[])
`interface RecipesResponse { recipes: IRecipe[] }`

...

`.then((response: AxiosResponse<RecipesResponse>) => response.data.recipes)`

2022-11-07 10:57 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +        recipes = recipes.filter((x) => x.title.toUpperCase().includes(
вместо иксов и прочих, ни о чем не говорящих букв, можно сразу использовать деструктуризацию
` recipes = recipes.filter(({ title }) => title.toUpperCase().includes(`

2022-11-07 10:57 UTC, alinadk12 commented on src/domain/entity/recipe/RecipesMobxStore.ts
> +      if (filters.nameFilter) {
тут можно использовать деструктуризацию, чтобы каждый раз к объекту не обращаться

```
 if (filters) {
      const { nameFilter, cuisinesFilter, calFilter } = filters;

      if (nameFilter) {}

      if (cuisinesFilter) {}

      if (calFilter) {}
    }
```

2022-11-11 07:45 UTC, alinadk12 requested changes

2022-11-11 07:45 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +        caloricFilter: state.caloricFilter,
лучше писать `...state` на случай, если понадобиться расширить state

2022-11-11 08:05 UTC, alinadk12 approved these changes

2022-11-11 08:05 UTC, merged