Add routes and fix interface drawbacks
Ray-Janson/AirRecipes2.0 pull request #8
Opened 2022-11-11 08:52 UTC by Ray-Janson

2022-11-11 09:12 UTC, alinadk12 requested changes

2022-11-11 09:12 UTC, alinadk12 commented on src/components/containers/contentContainer/ContentContainerController.tsx
> +  React.useEffect(() => {
`useEffect` импортни из `React`

2022-11-11 09:12 UTC, alinadk12 commented on src/components/filterForm/FilterFormController.tsx
> +    return () => {
отступ

2022-11-11 09:12 UTC, alinadk12 commented on src/components/header/HeaderController.tsx
>      return () => {
отступ

2022-11-11 09:12 UTC, alinadk12 commented on src/components/header/HeaderView.tsx
> +          <Link href="/"><Typography variant="h1">Air Recipes</Typography></Link>
```
<Link href="/">
  <Typography variant="h1">Air Recipes</Typography>
</Link>
```

2022-11-11 09:12 UTC, alinadk12 commented on src/domain/entity/pageElements/PageElementsMobxStore.ts
> +  @observable private _contentContainer: HTMLDivElement | null = null;
объявление поля перенеси перед конструктором

2022-11-11 09:12 UTC, alinadk12 commented on src/theme/theme.ts
> +          zIndex: '2000 !important',
Без `!important` не обойтись? Если есть возможность его не использовать, то лучше не использовать

2022-11-14 08:53 UTC, Ray-Janson commented on src/theme/theme.ts
> +          zIndex: '2000 !important',
Переопределяю дефолтные стили у backdrop'а формы в Mui theme. Без `imporant` именно `zIndex` не переопределяется. Другие варианты не сработали

2022-11-14 10:12 UTC, closed without merging